In [1]:
import pylegend
frame = pylegend.samples.pandas_api.northwind_orders_frame()

In [1]:
# Rank all columns (replaces values with ranks)
frame.filter(items=["Order Id"]).rank().head(5).to_pandas()

   Order Id
0         1
1         2
2         3
3         4
4         5

In [1]:
# Append a percentage rank column via Series assignment
frame["Order Rank"] = frame["Order Id"].rank(pct=True)
frame.head(5).to_pandas()

,Order Id,Order Date,Required Date,Shipped Date,Ship Name,Order Rank
0,10248,1996-07-04,1996-08-01,1996-07-16,Vins et alcools Chevalier,0.0
1,10249,1996-07-05,1996-08-16,1996-07-10,Toms Spezialitäten,0.001206
2,10250,1996-07-08,1996-08-05,1996-07-12,Hanari Carnes,0.002413
3,10251,1996-07-08,1996-08-05,1996-07-15,Victuailles en stock,0.003619
4,10252,1996-07-09,1996-08-06,1996-07-11,Suprêmes délices,0.004825