In [1]:
import pylegend
frame = pylegend.samples.pandas_api.northwind_orders_frame()

In [1]:
# Dict-based aggregation on groups
frame.groupby("Ship Name").aggregate(
    {"Order Id": "count"}
).head(5).to_pandas()

                            Ship Name  Order Id
0                Alfred's Futterkiste         5
1                 Alfreds Futterkiste         1
2  Ana Trujillo Emparedados y helados         4
3             Antonio Moreno Taquería         7
4                     Around the Horn        13

In [1]:
# Multiple aggregations per column
frame.groupby("Ship Name").aggregate(
    {"Order Id": ["min", "max"]}
).head(5).to_pandas()

                            Ship Name  min(Order Id)  max(Order Id)
0                Alfred's Futterkiste          10692          11011
1                 Alfreds Futterkiste          10643          10643
2  Ana Trujillo Emparedados y helados          10308          10926
3             Antonio Moreno Taquería          10365          10856
4                     Around the Horn          10355          11016

In [1]:
# Broadcast a single function to all non-grouping columns
frame.groupby("Ship Name", sort=False).aggregate("count").head(5).to_pandas()

,Ship Name,Order Id,Order Date,Required Date,Shipped Date
0,Alfred's Futterkiste,5,5,5,5
1,Alfreds Futterkiste,1,1,1,1
2,Ana Trujillo Emparedados y helados,4,4,4,4
3,Antonio Moreno Taquería,7,7,7,7
4,Around the Horn,13,13,13,13