In [1]:
import pylegend
frame = pylegend.samples.legendql_api.northwind_orders_frame()

In [1]:
# Skip first 5 rows (default), then show next 5
frame.drop().head(5).to_pandas()

   Order Id Order Date Required Date Shipped Date               Ship Name
0     10253 1996-07-10    1996-07-24   1996-07-16           Hanari Carnes
1     10254 1996-07-11    1996-08-08   1996-07-23       Chop-suey Chinese
2     10255 1996-07-12    1996-08-09   1996-07-15      Richter Supermarkt
3     10256 1996-07-15    1996-08-12   1996-07-17  Wellington Importadora
4     10257 1996-07-16    1996-08-13   1996-07-22        HILARION-Abastos

In [1]:
# Skip first 10 rows
frame.drop(10).head(5).to_pandas()

   Order Id Order Date Required Date Shipped Date                   Ship Name
0     10258 1996-07-17    1996-08-14   1996-07-23                Ernst Handel
1     10259 1996-07-18    1996-08-15   1996-07-25  Centro comercial Moctezuma
2     10260 1996-07-19    1996-08-16   1996-07-29          Ottilies Käseladen
3     10261 1996-07-19    1996-08-16   1996-07-30                 Que Delícia
4     10262 1996-07-22    1996-08-19   1996-07-25  Rattlesnake Canyon Grocery