In [1]:
import pylegend
frame = pylegend.samples.pandas_api.northwind_orders_frame()

In [1]:
# Select specific columns
frame.loc[:, "Ship Name"].head(3).to_pandas()

                   Ship Name
0  Vins et alcools Chevalier
1         Toms Spezialitäten
2              Hanari Carnes

In [1]:
# Filter rows with a boolean condition and select columns
frame.loc[frame["Order Id"] > 10300, ["Order Id", "Ship Name"]].head(5).to_pandas()

   Order Id               Ship Name
0     10301       Die Wandernde Kuh
1     10302        Suprêmes délices
2     10303     Godos Cocina Típica
3     10304     Tortuga Restaurante
4     10305  Old World Delicatessen

In [1]:
# Filter rows with a callable
frame.loc[
    lambda x: x["Ship Name"].startswith("A"),
    ["Order Id", "Ship Name"]
].head(5).to_pandas()

   Order Id                           Ship Name
0     10308  Ana Trujillo Emparedados y helados
1     10355                     Around the Horn
2     10365             Antonio Moreno Taquería
3     10383                     Around the Horn
4     10453                     Around the Horn

In [1]:
# Boolean column mask
frame.loc[:, [True, False]].head(3).to_pandas()

IndexError: Boolean index has wrong length: 2 instead of 5