In [1]:
import pylegend
frame = pylegend.samples.pandas_api.northwind_orders_frame()

In [1]:
# Expanding sum over all numeric columns
frame.filter(
    items=["Order Id"]
).expanding(order_by="Order Id").aggregate("sum").head(5).to_pandas()

   Order Id
0     10248
1     20497
2     30747
3     40998
4     51250

In [1]:
# Rolling mean with a window of 3
frame.filter(
    items=["Order Id"]
).rolling(3, order_by="Order Id").aggregate("mean").head(5).to_pandas()

   Order Id
0   10248.0
1   10248.5
2   10249.0
3   10250.0
4   10251.0