In [1]:
import pylegend
frame = pylegend.samples.pandas_api.northwind_orders_frame()

In [1]:
# Single named aggregation
frame.groupby("Ship Name")["Order Id"].aggregate(
    "sum"
).head(5).to_pandas()

                            Ship Name  Order Id
0                Alfred's Futterkiste     54192
1                 Alfreds Futterkiste     10643
2  Ana Trujillo Emparedados y helados     42618
3             Antonio Moreno Taquería     74195
4                     Around the Horn    139254

In [1]:
# Multiple aggregations
frame.groupby("Ship Name")["Order Id"].aggregate(
    ["min", "max", "count"]
).head(5).to_pandas()

,Ship Name,min(Order Id),max(Order Id),count(Order Id)
0,Alfred's Futterkiste,10692,11011,5
1,Alfreds Futterkiste,10643,10643,1
2,Ana Trujillo Emparedados y helados,10308,10926,4
3,Antonio Moreno Taquería,10365,10856,7
4,Around the Horn,10355,11016,13