In [1]:
import pylegend
frame = pylegend.samples.legendql_api.northwind_orders_frame()

In [1]:
# Add a single computed column
extended = frame.extend(("Ship Name Upper", lambda r: r["Ship Name"].upper()))
extended.select(["Ship Name", "Ship Name Upper"]).head(5).to_pandas()

                   Ship Name            Ship Name Upper
0  Vins et alcools Chevalier  VINS ET ALCOOLS CHEVALIER
1         Toms Spezialitäten         TOMS SPEZIALITÄTEN
2              Hanari Carnes              HANARI CARNES
3       Victuailles en stock       VICTUAILLES EN STOCK
4           Suprêmes délices           SUPRÊMES DÉLICES

In [1]:
# Add multiple computed columns
cols = ["Ship Name", "Ship Name Upper", "Ship Name Lower"]
frame.extend([
    ("Ship Name Upper", lambda r: r["Ship Name"].upper()),
    ("Ship Name Lower", lambda r: r["Ship Name"].lower())
]).select(cols).head(5).to_pandas()

,Ship Name,Ship Name Upper,Ship Name Lower
0,Vins et alcools Chevalier,VINS ET ALCOOLS CHEVALIER,vins et alcools chevalier
1,Toms Spezialitäten,TOMS SPEZIALITÄTEN,toms spezialitäten
2,Hanari Carnes,HANARI CARNES,hanari carnes
3,Victuailles en stock,VICTUAILLES EN STOCK,victuailles en stock
4,Suprêmes délices,SUPRÊMES DÉLICES,suprêmes délices