In [1]:
import pylegend
frame = pylegend.samples.pandas_api.northwind_orders_frame()

In [1]:
# Add a constant column
frame.assign(constant=lambda x: 100).head(3).to_pandas()

,Order Id,Order Date,Required Date,Shipped Date,Ship Name,constant
0,10248,1996-07-04,1996-08-01,1996-07-16,Vins et alcools Chevalier,100
1,10249,1996-07-05,1996-08-16,1996-07-10,Toms Spezialitäten,100
2,10250,1996-07-08,1996-08-05,1996-07-12,Hanari Carnes,100

In [1]:
# Add a computed column derived from existing columns
frame.assign(
    ship_upper=lambda x: x.get_string("Ship Name").upper()
).head(3).to_pandas()

,Order Id,Order Date,Required Date,Shipped Date,Ship Name,ship_upper
0,10248,1996-07-04,1996-08-01,1996-07-16,Vins et alcools Chevalier,VINS ET ALCOOLS CHEVALIER
1,10249,1996-07-05,1996-08-16,1996-07-10,Toms Spezialitäten,TOMS SPEZIALITÄTEN
2,10250,1996-07-08,1996-08-05,1996-07-12,Hanari Carnes,HANARI CARNES

In [1]:
# Overwrite an existing column
frame.assign(
    **{"Ship Name": lambda x: x.get_string("Ship Name").upper()}
).head(3).to_pandas()

   Order Id Order Date Required Date Shipped Date                  Ship Name
0     10248 1996-07-04    1996-08-01   1996-07-16  VINS ET ALCOOLS CHEVALIER
1     10249 1996-07-05    1996-08-16   1996-07-10         TOMS SPEZIALITÄTEN
2     10250 1996-07-08    1996-08-05   1996-07-12              HANARI CARNES