In [1]:
import pylegend
frame = pylegend.samples.pandas_api.northwind_orders_frame()

In [1]:
# Single named aggregation
frame["Order Id"].aggregate("sum").to_pandas()

   Order Id
0   8849875

In [1]:
# Multiple aggregations via a list
frame["Order Id"].aggregate(["sum", "min", "max"]).to_pandas()

   sum(Order Id)  min(Order Id)  max(Order Id)
0        8849875          10248          11077

In [1]:
# Lambda aggregation
frame["Order Id"].aggregate(lambda x: x.count()).to_pandas()

   Order Id
0       830